"""add candidate job matches

Revision ID: 212ff01d5722
Revises: c4aa614eb5b7
Create Date: 2026-09-05 05:05:09.925952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '212ff01d5722'
down_revision: Union[str, Sequence[str], None] = 'c4aa614eb5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_job_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('skill_score', sa.Float(), nullable=False),
    sa.Column('experience_score', sa.Float(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('matched_skills', sa.JSON(), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('experience_status', sa.String(), nullable=False),
    sa.Column('match_level', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'job_id', name='uq_candidate_job_match')
    )
    op.create_index(op.f('ix_candidate_job_matches_candidate_id'), 'candidate_job_matches', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_job_matches_id'), 'candidate_job_matches', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_job_matches_job_id'), 'candidate_job_matches', ['job_id'], unique=False)
    op.create_index(op.f('ix_candidate_job_matches_match_level'), 'candidate_job_matches', ['match_level'], unique=False)
    op.create_index(op.f('ix_candidate_job_matches_overall_score'), 'candidate_job_matches', ['overall_score'], unique=False)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_job_matches_overall_score'), table_name='candidate_job_matches')
    op.drop_index(op.f('ix_candidate_job_matches_match_level'), table_name='candidate_job_matches')
    op.drop_index(op.f('ix_candidate_job_matches_job_id'), table_name='candidate_job_matches')
    op.drop_index(op.f('ix_candidate_job_matches_id'), table_name='candidate_job_matches')
    op.drop_index(op.f('ix_candidate_job_matches_candidate_id'), table_name='candidate_job_matches')
    op.drop_table('candidate_job_matches')
    # ### end Alembic commands ###
