"""fix: use timezone aware timestamps

Revision ID: a3a071bde1ae
Revises: 527fd3dd85ae
Create Date: 2026-09-08 03:33:16.182999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a071bde1ae'
down_revision: Union[str, Sequence[str], None] = '527fd3dd85ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
